# Generated by Django 5.2.4 on 2025-09-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_name_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='course_logo')),
                ('Course_Title', models.CharField(max_length=255)),
                ('Course_syllabus', models.CharField()),
                ('course_intro', models.CharField()),
                ('Course_description', models.TextField()),
                ('Course_level', models.CharField(max_length=255)),
                ('Course_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='dp')),
                ('First_Name', models.CharField()),
                ('Last_Name', models.CharField()),
                ('Occupation', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField()),
                ('location', models.CharField()),
                ('member_since', models.CharField()),
                ('mobile', models.CharField()),
                ('goal', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Modules_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_Index', models.IntegerField()),
                ('Module_Title', models.CharField(max_length=255)),
                ('Module_Detail', models.CharField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Card.course_name_list')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Index', models.IntegerField()),
                ('Front', models.TextField()),
                ('Back', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Card.course_name_list')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Card.modules_list')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modules_list',
            constraint=models.UniqueConstraint(fields=('course', 'Module_Title'), name='unique_module_title_per_course'),
        ),
        migrations.AddConstraint(
            model_name='modules_list',
            constraint=models.UniqueConstraint(fields=('course', 'Module_Index'), name='unique_module_index_per_course'),
        ),
    ]
